// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcCoWZv0fl_SXlkCBYoJD82YQVPoeJrrw',
    appId: '1:850918062154:web:d30a8c85a40bb7d0828eb3',
    messagingSenderId: '850918062154',
    projectId: 'calorietracker-3eec7',
    authDomain: 'calorietracker-3eec7.firebaseapp.com',
    storageBucket: 'calorietracker-3eec7.appspot.com',
    measurementId: 'G-43YXY7R97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeJotvvMK79eHVAs0yW_OWM5cAfexDRE',
    appId: '1:850918062154:android:34c320f16f70ce85828eb3',
    messagingSenderId: '850918062154',
    projectId: 'calorietracker-3eec7',
    storageBucket: 'calorietracker-3eec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2H28aUJQaquA97TpTp6WII8EYYZkuC4',
    appId: '1:850918062154:ios:0b4f25d6e2b4b977828eb3',
    messagingSenderId: '850918062154',
    projectId: 'calorietracker-3eec7',
    storageBucket: 'calorietracker-3eec7.appspot.com',
    iosClientId: '850918062154-ogkrfatnmve8f0g6772nlbfr1qclmqs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb2H28aUJQaquA97TpTp6WII8EYYZkuC4',
    appId: '1:850918062154:ios:0b4f25d6e2b4b977828eb3',
    messagingSenderId: '850918062154',
    projectId: 'calorietracker-3eec7',
    storageBucket: 'calorietracker-3eec7.appspot.com',
    iosClientId: '850918062154-ogkrfatnmve8f0g6772nlbfr1qclmqs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );
}
